### ISSUE TITLE
Error when edit value of node

### ISSUE THREAD

**Issue by nvcken** [gliviu/json-easy-filter#1]
```
var res = new JefNode(filter).filter(function(node) {
   if (node.has('text')) 
       node.value.text = ObjectID("abc");
});
```

Got error :     "message": "Cannot read property 'path' of undefined",

**Comment by nvcken** [comment]
It occurs when I set value type is ObjectID.
I will debug more.

**Comment by gliviu** [comment]
Hello I have some business right now but i ll take a look on sunday. Just
let me know if you find more.

Liviu

**Comment by githubtest4324** [comment]
The problem is most probably that you change the structure of the json object during filtering operation. This is not supported because json-easy-filter keeps an internal representation of the wrapped object. Following code will cause this exception:

``` js
var obj = {
    s1 : 'v1',
    o2 : {
        text : 'v2'
    }
};

var root = new JefNode(obj);
var res = root.filter(function(node) {
    if (node.has('text')){
        node.value.text = {x:'y'};
    }
});
```

Solution - remember nodes that have to be changed and update them later:

``` js
var root = new JefNode(obj);
var modif = [];
var res = root.filter(function(node) {
    if (node.has('text')){
        modif.push({parent: node.value, newVal: {x:'y'}})
    }
});
for (var i = 0; i < modif.length; i++) {
    var elem = modif[i];
    elem.parent.text = elem.newVal; 

}
```

**Comment by nvcken** [comment]
ok, thanks
